### ISSUE TITLE
LMDB property issues are breaking search

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2549]
Property `stroom.search.resultStore.lmdb.readerBlockedByWriter` cannot be set via the props UI.

Additionally the property must be set to false in the config.yml as the defaulted value is somehow being set to true

**Comment by at055612** [comment]
Need to make search throw an ex if this prop is set to true prior to creating the env.  Can't risk someone setting it.

Would be nice to know why having this blocking enabled is taking down a node.

**Comment by at055612** [comment]
It seems that use of a cursor, txn or dbi after the env is closed will likely result in the jvm crashing.  Have raised an issue and PR on lmdbjava as that seems the best place to fix it.

**Comment by at055612** [comment]
Default config now looks like:
```yml
      lmdb:
        localDir: "reference_data"
        maxReaders: 150
        maxStoreSize: "50G"
        readAheadEnabled: true
        readerBlockedByWriter: true

      lmdb:
        localDir: "search_results"
        maxReaders: 10
        maxStoreSize: "10G"
        readAheadEnabled: true
```
`readerBlockedByWriter` is not configurable for search, hard coded to `false`.  `maxDbs` now not configurable for either as this is a compile time thing.
