### ISSUE TITLE
Get travis to do docker builds for multiple branches

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#291]
It would be good if travis could build docker images for the release branches as well as latest on master.  It could look for branches == 'master' or matching [0-9]{1,2}\.[0-9]{1,2} and then build those that match.

example travis cofnig below, though would need to prevent it building for non-matching branches.
```
env:
  global:
    - secure: "........." # DOCKER_EMAIL
    - secure: "........." # DOCKER_USER
    - secure: "........." # DOCKER_PASS
    - COMMIT=${TRAVIS_COMMIT::8}

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=gchq/stroom
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
```
