### ISSUE TITLE
Make rendered Documentation support select & copy

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#3518]

**Comment by at055612** [comment]
```css
.markdown-container {
  overflow-y: scroll;
  background-color: var(--markdown-background__color);
  white-space: normal !important;
  user-select: text !important;
  -webkit-user-select: text !important;
  -moz-user-select: text !important;
  -ms-user-select: text !important;
}

.markdown p {
  user-select: text !important;
  -webkit-user-select: text !important;
  -moz-user-select: text !important;
  -ms-user-select: text !important;
}
```
