### ISSUE TITLE
Auth proxy `fetchClientCredsToken` does not return token when the internal identity provider is used

### ISSUE THREAD

**Issue by p-kimberley** [gchq/stroom#4825]
There's an issue with the Stroom K8s operator failing to work where the internal IdP is used. See https://github.com/gradata-systems/stroom-k8s-operator/issues/52. When the Stroom K8s startup hook calls `/api/authproxy/v1/noauth/fetchClientCredsToken` with `clientId` and `clientSecret` in the body, [this line](https://github.com/gchq/stroom/blob/fe7e6d4c582b8c549cd21ff129da598b8ff0ef31/stroom-security/stroom-security-impl/src/main/java/stroom/security/impl/AuthProxyServiceImpl.java#L106) is checking the provided credentials against the configured values, as you'd expect.

Unfortunately OpenIdConfiguration::getClientId() and OpenIdConfiguration::getClientSecret() are returning a value like: `dgiZiJxhQmoLZrZZAARYRJSGr7UFLw1xjrQjhE7k.client-id.apps.stroom-idp`, which starts with a series of randomly-generated characters. The API method returns 400: bad request.

There's no way of knowing in advance what this random series of characters will be, rendering this authproxy method useless where the internal IdP is used.

Can we change the behaviour to just use the configured clientId and clientSecret instead instead of generating values for these? I assume the current implementation was done for security reasons. We could consider using environment variable or file references in configuration instead. For example:

```yaml
openId:
  clientId: "stroom"
  clientSecretFile: "/var/run/secrets/stroom-openid-client-secret"
```

**Comment by at055612** [comment]
The code will respect the client(Id|Secret) config props if you set them.  If you don't set them it auto-generates random ones.  Whether configured or randomly generated, the creds get stored in the oauth_client table and the values in that table are used on future boots regardless of config.
If you want to set your own client(Id|Secret) you would need to clear this table and set the config props on all nodes.
Whether the k8s operator should be using stroom's internal client creds is another question.  Maybe the config should allow for creating additional sets of client creds.

```yaml
    authentication:
      openId:
        clientId: "myClientId"
        clientSecret: "myClientSecret"
        identityProviderType: "INTERNAL_IDP"
```

![Image](https://github.com/user-attachments/assets/b17199f5-c7a7-4f15-8ba8-6dc7d656bf86)
