### ISSUE TITLE
Add validation for data receipt header values

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#4917]
Some headers are now used to set values in the FeedDoc.
 
* `Classification`
* `Schema`
* `SchemaVersion`

Each of these should have a dedicated config prop with a regex pattern to control the allowed values.
If the prop is set then any data with an invalid header value should be rejected, in the same way that an unknown feed is rejected.
This should probably be done in the FeedStatusCheck.
Thought is needed on the implications for zips sent to proxy containing files for many feeds.

These values also can be set in the FeedDoc in the UI.  The UI ought to employ the same validation, but must allow for existing values that do not pass validation. 

Other headers such as `AccountId` and `Component` are not first class citizens so to validate them we will need a map type config prop like
```
  receive:
    headerValidationPatterns:
      component: "[A-Z_]+"
      accountid: "[0-9]+"
```
